version: '3'
services:
  mongodbusers:
    image: mongo:latest
    container_name: 'mongodbusers'
    ports:
      - 27017:27017
  api:
    build:
      context: api
    ports:
      - 8080:8080
    restart: on-failure
    volumes: 
      - ./api:/app
      - /app/node_modules
  users1:
    build:
      context: users
    environment:
      PORT: 4001
    ports:
      - 4001:4001
    restart: on-failure
    depends_on:
      - 'mongodbusers'
    volumes: 
      - ./users:/app
      - /app/node_modules
  users2:
    build:
      context: users
    environment:
      PORT: 4002
    ports:
      - 4002:4002
    restart: on-failure
    depends_on:
      - 'mongodbusers'
    volumes: 
      - ./users:/app
      - /app/node_modules
  users3:
    build:
      context: users
    environment:
      PORT: 4003
    ports:
      - 4003:4003
    restart: on-failure
    depends_on:
      - 'mongodbusers'
    volumes: 
      - ./users:/app
      - /app/node_modules